# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'VERSION >= v\"0.7.0-\" && using Pkg;
      VERSION < v\"0.7.0-\" && cd(Pkg.dir("RingBuffers"));
      Pkg.add("Coverage");
      using Coverage;
      Codecov.submit(process_folder())'
